var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/faq/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0rmyaog._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0w62c.w.js")
R.c("server/chunks/ssr/[root-of-the-server]__0ewjpmr._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0zgvpt1._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0i7sn5.._.js")
R.c("server/chunks/ssr/_02_pzur._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_faq_page_actions_03t0wwz.js")
R.m(37241)
module.exports=R.m(37241).exports
