var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/about-us/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__13i92t9._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0b4e2cn.js")
R.c("server/chunks/ssr/[root-of-the-server]__0ewjpmr._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0zgvpt1._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0i7sn5.._.js")
R.c("server/chunks/ssr/_02_pzur._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_about-us_page_actions_0gem~m-.js")
R.m(77526)
module.exports=R.m(77526).exports
